### ISSUE TITLE
yarn install fails because of untyped void-function variable

### ISSUE THREAD

**Issue by GavinRay97** [8base/cli#48]
**Describe the bug**
`noImplicitAny: true` in `tsconfig.json` causes `spinner = new Ora()` to fail. Found in `src/common/context.ts:42`.

**To Reproduce**
1. Attempt to `yarn install`

**Expected behavior**
The `cli` package successfully installs

**Screenshots**
![image](https://user-images.githubusercontent.com/26604994/66617736-508b9680-eba4-11e9-8ff7-aecd4fc73b24.png)
![image](https://user-images.githubusercontent.com/26604994/66617837-c263e000-eba4-11e9-8eed-5b6192772f17.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/26604994/66617911-0eaf2000-eba5-11e9-8268-bd041aa6f65d.png)

**Comment by GavinRay97** [comment]
Fixing this still leaves the other error, which seems to be a problem in `apollo-link` typings:

*../node_modules/apollo-link/lib/types.d.ts:22:56 - error TS2315: Type 'ExecutionResult' is not generic.*
https://github.com/apollographql/apollo-link/issues/910

**Comment by GavinRay97** [comment]
Second issue solved with `yarn upgrade --latest @types/graphql` :+1:

**Comment by lesha1201** [comment]
@GavinRay97 The CLI uses npm. So I think using yarn you've installed latest version of typescript ignoring package-lock.json. I will check if using npm should help

**Comment by lesha1201** [comment]
@GavinRay97 Yes, issue is with installing without lock file. If you want to use yarn you can convert package-lock.json to yarn.lock using `yarn import`. But in that case I recommend to use `npm` in order to have one lock file.

Another issue you can encounter is that for some reason there is a devDependency `node-sass` (I don't know why it's there). Version in lock file is 4.10 and you're using node v12. In order to successfully compile node-sass with node v12 you need node-sass version 4.12+ (https://github.com/sass/node-sass). So you can either change node version using `nvm` or delete/downgrade temporarly while installing packages.
